---
title: "R Notebook"
output: github_document
editor_options: 
  chunk_output_type: inline
---

```{r setup}
library(tidyverse)
library(readxl)
library(directlabels)
```

## Lese inn data og tranformere fra wide til long format

```{r read-data}
# antar at "lokalkommuner.xlsx" er i working directory
x <- read_xlsx(path = "lokalkommuner.xlsx")
# ser på 5 første linjer
head(x, n = 5)
# går fra wide til long
x_l <- pivot_longer(x, cols = `1951`:`2020`, names_to = "år", values_to = "befolkning")
# befolkning as integer, år as date
x_l$befolkning. <- as.integer(x_l$befolkning)
x_l$år <- as.Date(x_l$år, format = "%Y")
# set name first variable
names(x_l)[1] <- "kommune"
#  set missing to 0
x_l[is.na(x_l)] <- 0
head(x_l, n = 5)
```

## Plot av dataene

### Strand

```{r plot-strand}
plot_data <- x_l %>% 
  filter(år > "1960-09-22") %>%
  filter(år < "2020-09-22") %>%
  filter(kommune %in% c("Strand"))

ggplot(data = plot_data, mapping = aes(x = år, y = befolkning, group = kommune)) +
  geom_line(mapping = aes(colour = kommune), size = 0.5) +
  theme(
    legend.justification = c(0, 0),
    legend.position = c(0.05, 0.75)
    #legend.position = "none"
  )
```

### Flere kommuner

```{r plot-flere}
plot_data <- x_l %>% 
  filter(år > "1965-09-22") %>%
  filter(år < "2020-09-22") %>%
  filter(kommune %in% c("Strand", "Finnøy", "Rennesøy"))

ggplot(data = plot_data, mapping = aes(x = år, y = befolkning, group = kommune)) +
  geom_line(mapping = aes(colour = kommune), size = 0.5) +
  theme(
    legend.justification = c(0, 0),
    legend.position = c(0.05, 0.7)
    #legend.position = "none"
  )
```
### Alle

Dropper dem med skalert i navnet.

```{r plot-begge}
plot_data <- x_l %>% 
  filter(år > "1950-09-22") %>%
  filter(år < "2020-09-22") 

plot_data <- plot_data[str_detect(plot_data$kommune, "_skalert", negate = TRUE),]

ggplot(data = plot_data, mapping = aes(x = år, y = befolkning, group = kommune)) +
  geom_line(mapping = aes(colour = kommune), size = 1.25) +
  geom_label(mapping = aes(x = år, y = befolkning, label = kommune))
```
### Utvalg

#### Make subset

```{r subset}
x_l_s <- x_l %>%
  filter(år < "2020-09-22") %>%
  filter(år >= "1951-09-22") %>%
  filter(kommune %in% c("Askøy", "Fjell", "Finnøy", "Tysnes"))
```


```{r plot-utvalg}
g1 <- ggplot(data = filter(x_l_s, år < "2020-09-22" & år > "1951-09-22"), mapping = aes(x = år, y = befolkning, group = kommune)) +
  geom_line(mapping = aes(colour = kommune), size = 0.75)
g1
```

```{r themed}
themed <- g1 +
  theme(
    legend.justification = c(0, 1),
    legend.position = c(0, 1)
  )
themed

```
```{r bw}
g1_bw <- g1 +
    theme_linedraw() +
    theme(
    legend.justification = c(0, 1),
    legend.position = c(0.05, 0.95)
  ) 

g1_bw
```

